### PR TITLE
[17.0][MIG] web_company_color: Migration to 17.0 

### PR DESCRIPTION
**Pull request by psugne**
Inspiration gotten from OCA [commit](https://github.com/OCA/web/pull/2813/commits/44490776d8d9843825b183fb6e11d361d129f8b1)

### CODE REVIEW

**Comment by psugne** [comment]
Please check only [1d483d7](https://github.com/versada/web/pull/8/commits/1d483d7e07ac18d299bad18d607398b4f48ae91b) commit.

**Comment by psugne** [comment]
Switching reviewers as @oerp-odoo is off today, I'm a bit on an urgent side and you @maciej-wichowski are already related with web :)

**Review by maciej-wichowski — APPROVED** [review]
Please do not share links to our internal services on public repositories :)

**Comment by psugne** [comment]
@maciej-wichowski is is not a public repo, it's 17.0-versada branch which will be used only inside :)
Regarding OCA, PR is already done not by me.

**Comment by maciej-wichowski** [comment]
> @maciej-wichowski is is not a public repo, it's 17.0-versada branch which will be used only inside :) Regarding OCA, PR is already done not by me.

Yes, I know, but it is publicly visible. And we don't want to show our internal services to everyone :) It's not even my invention, Andrius pointed it to me some time ago. So please remove link to hive from your first comment.

**Pull request merged**
